services:
  frontend:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./repos/frontend
    networks:
      traefik:
      portfolio:
    labels:
      - "traefik.enable=true"
      - "traefik.routers.${APP_ID}.rule=Host(`${APP_DOMAIN}`) || Host(`www.${APP_DOMAIN}`)"
      - "traefik.routers.${APP_ID}.entrypoints=https"
      - "traefik.routers.${APP_ID}.tls=true"
      - "traefik.http.services.${APP_ID}.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
  portfolio:
