apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-portfolio
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
- serviceaccount.yaml
- redirect-middleware.yaml
- deployment-backend.yaml
- service-backend.yaml
- ingress-backend.yaml
- ingress-backend-ssh.yaml
images:
- name: cr.cloud.martinpetr.dev/portfolio-frontend
  newName: cr.cloud.martinpetr.dev/portfolio-frontend
  newTag: e600b8f144c8a406518ebd7b4bb05d875ab6620e
- name: cr.cloud.martinpetr.dev/portfolio-backend
  newName: cr.cloud.martinpetr.dev/portfolio-backend
  newTag: latest
