apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-portfolio
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
- serviceaccount.yaml
- redirect-middleware.yaml
images:
- name: cr.cloud.martinpetr.dev/portfolio-frontend
  newName: cr.cloud.martinpetr.dev/portfolio-frontend
  newTag: 5bb74cf43135beed074a322f211f056320536707
