apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-portfolio
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
- serviceaccount.yaml
- redirect-middleware.yaml
- deployment-backend.yaml
- service-backend.yaml
- ingress-backend.yaml
- ingress-backend-ssh.yaml
images:
- name: cr.cloud.martinpetr.dev/portfolio-backend
  newName: cr.cloud.martinpetr.dev/portfolio-backend
  newTag: a8dd219db559295ad6dfab5deb785559d4b593e4
- name: cr.cloud.martinpetr.dev/portfolio-frontend
  newName: cr.cloud.martinpetr.dev/portfolio-frontend
  newTag: a8dd219db559295ad6dfab5deb785559d4b593e4
