name: GitOps Build & Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "kubernetes/**"
      - "flux-system/**"

permissions:
  contents: write

jobs:
  build-and-update-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build & Push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: repos/frontend
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/portfolio-frontend:${{ github.sha }}
      - name: Build & Push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: repos/backend
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/portfolio-backend:${{ github.sha }}
      - name: Update & Commit kustomize
        run: |
          cd kubernetes

          kustomize edit set image ${{ secrets.REGISTRY_URL }}/portfolio-frontend=${{ secrets.REGISTRY_URL }}/portfolio-frontend:${{ github.sha }}
          kustomize edit set image ${{ secrets.REGISTRY_URL }}/portfolio-backend=${{ secrets.REGISTRY_URL }}/portfolio-backend:${{ github.sha }}

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git commit -am "chore: update image tags to ${{ github.sha }} [skip ci]"

          git push origin main
